### ISSUE TITLE
Manifest generation fails if deployment is missing resource block

### ISSUE THREAD

**Issue by jtary** [akash-network/akashjs#40]
If an SDL doesn't contain a resource block with the same name as the service, the look up will fail in a way that causes an exception. Example SDL below:

```yaml
version: '2.0'
services:
  tetris-main:
    image: bsord/tetris
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    tetris:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
      pricing:
        tetris:
          denom: uakt
          amount: 10000
deployment:
  tetris:
    akash:
      profile: tetris
      count: 1
```

In this case, the generation should not cause an error.
